name-template: 'v$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
version-template: '2024.$MAJOR.$MINOR'
categories:
  - title: '🚨 BREAKING CHANGES'
    labels:
      - 'breaking 🚨'
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Fixes'
    labels:
      - 'fix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels: 
      - 'chore'
      - 'ci'
      - 'docs'
      - 'test'
change-template: '- $TITLE #$NUMBER @$AUTHOR'
version-resolver:
  major:
    labels:
      - 'breaking'
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'fix'
      - 'bug'
      - 'chore'
template: |
  ##  What's Changed

  $CHANGES