//
//  Item.swift
//  iHog
//
//  Created by Jay Wilson on 11/10/24.
//
//

import Foundation
import SwiftData

// this class isn't used and is the autogenerated class by xcode, but it was published with cloudkit so I guess it stays forever...
@Model final class Item {
  var timestamp: Date?

  init(timestamp: Date? = nil) {
    self.timestamp = timestamp
  }
}
