name: "Danger"
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    name: Danger Swift
    steps:
      - uses: actions/checkout@v4
      - name: Danger
        uses: danger/swift@3.18.0
        with:
          args: --failOnErrors --no-publish-check
        env:
          GITHUB_TOKEN: ${{ secrets.DANGER_BOT }}
